### ISSUE TITLE
Issue when I run python object_detection_demo_yolov3_async.py 

### ISSUE THREAD

**Issue by nitipol012** [TNTWEN/OpenVINO-YOLOV4#22]
I've converted my custom data on the YoloV4 model it's worked. but when I run python object_detection_demo_yolov3_async.py  I got this error 

[ INFO ] Creating Inference Engine...
[ INFO ] Loading network
[ INFO ] Preparing inputs
[ INFO ] Loading model to the plugin
[ INFO ] Starting inference...
To close the application, press 'CTRL+C' here or switch to the output window and press ESC key
To switch between min_latency/user_specified modes, press TAB key in the output window
Traceback (most recent call last):
  File "object_detection_demo_yolov3_async.py", line 518, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo_yolov3_async.py", line 398, in main
    args.keep_aspect_ratio)
  File "object_detection_demo_yolov3_async.py", line 233, in get_objects
    out_blob = out_blob.buffer.reshape(net.layers[net.layers[layer_name].parents[0]].out_data[0].shape)
ValueError: cannot reshape array of size 689520 into shape (1,21,52,52)

**Comment by Usernamezhx** [comment]
maybe you should change the yolo_v4_tiny.json classes num

**Comment by nitipol012** [comment]
Excellent. I follow your comment. It's worked. Thanksyou
