### ISSUE TITLE
run object_detection_demo_yolov3_async.py throw exception(ZeroDivisionError: division by zero)

### ISSUE THREAD

**Issue by youngerong** [TNTWEN/OpenVINO-YOLOV4#27]
python object_detection_demo_yolov3_async.py -i D://bike.avi -m frozen_darknet_yolov4_model.xml  -d CPU

(tf1.x) C:\Users\10048720\Downloads\OpenVINO-YOLOV4-master>python object_detecti
on_demo_yolov3_async.py -i D://bike.avi -m frozen_darknet_yolov4_model.xml  -d C
PU
[ INFO ] Creating Inference Engine...
[ INFO ] Loading network
[ INFO ] Preparing inputs
MFX: Can't initialize session
[ WARN:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\openc
v\modules\videoio\src\cap_msmf.cpp (682) CvCapture_MSMF::initStream Failed to se
t mediaType (stream 0, (320x240 @ 15) MFVideoFormat_RGB24(unsupported media type
)
[ INFO ] Loading model to the plugin
[ INFO ] Starting inference...
To close the application, press 'CTRL+C' here or switch to the output window and
 press ESC key
To switch between min_latency/user_specified modes, press TAB key in the output
window
[ INFO ]
[ INFO ] Mode: USER_SPECIFIED
[ INFO ] FPS: 0.0
Traceback (most recent call last):
  File "object_detection_demo_yolov3_async.py", line 518, in <module>
CreateFile() Error: 2
    sys.exit(main() or 0)
  File "object_detection_demo_yolov3_async.py", line 510, in main
CreateFile() Error: 2
    mode_info[mode_value].frames_count) * 1e3))
ZeroDivisionError: division by zero

**Comment by TNTWEN** [comment]
@youngerong 
This error generally occurs when there is an error in the model conversion


You can check whether your weight file is used correctly and whether the classes is set correctly 

Two places involve the classes setting

- when you run python convert_weights_pb.py --class_names cfg/coco.names --weights_file yolov4.weights --data_format NHWC replace coco.names with your own class file

- when you run `python "C:\Program Files (x86)\IntelSWTools\openvino_2020.4.287\deployment_tools\model_optimizer\mo.py" --input_model frozen_darknet_yolov4_model.pb --transformations_config yolov4.json --batch 1 --reverse_input_channels`
 make sure https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/6679af7e4cfca58e6aca832d983d04e3e1893a1f/yolov4.json#L6 is correct
