### ISSUE TITLE
Device didn't appear after reboot if I used MYRIAD rather than CPU

### ISSUE THREAD

**Issue by Hsien0802** [TNTWEN/OpenVINO-YOLOV4#59]
I am trying for using NCS2 with openvino_2021.4.752 version.
But I get an error about "device didn't appear after reboot", and it can work if I use CPU rather than MYRIAD.
```
(base) C:\Program Files (x86)\Intel\openvino_2021.4.752\inference_engine\demos\object_detection_demo\python>python object_detection_demo.py  -m C:\Users\Hsien\Desktop\frozen_darknet_yolov4_model.xml -i C:\Users\Hsien\Desktop\OCT_test_ing\yolo_v4\mp\1215539E-2.jpg -d MYRIAD -at yolov4
C:\Users\Hsien\anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
[ INFO ] Initializing Inference Engine...
[ INFO ] Loading network...
[ INFO ] Reading network from IR...
[ INFO ] Loading network to MYRIAD plugin...
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[0m
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[0m
[31mF: [xLink] [         0] [Scheduler00Thr] dispatcherResponseServe:852       no request for this response: XLINK_WRITE_RESP 1
[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=433
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=433
[0m
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   [0m
Event sending failed[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92    [0m
Duplicate id detected.
[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=433
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[0m
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=433
[0m
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_READ_REL_REQ
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[0m
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   [31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Event sending failedDuplicate id detected.
[0m
[0m
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467  [0m

WinUsb_WritePipe failed with error:=433
[35mE: [global] [         0] [EventRead00Thr] handleIncomingEvent:665  [0m
Assertion Failed: stream
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        [0m
Duplicate id detected.
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   [0m
Event sending failed[0m
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467  [0m

WinUsb_WritePipe failed with error:=433
[0m
[31mF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:92        Duplicate id detected.
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_CREATE_STREAM_REQ
[0m
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_READ_REL_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_CREATE_STREAM_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[35mE: [ncAPI] [         0] [] checkGraphMonitorResponse:1934  Graph monitor request returned error 556750880[0m
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_READ_REL_REQ
[35mE: [ncAPI] [         0] [] ncFifoAllocate:3081     myriad NACK
[0m
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_RESP
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[35mE: [ncAPI] [         0] [] checkGraphMonitorResponse:1934  Graph monitor request returned error 228373552[0m
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_READ_REL_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [ncAPI] [         0] [] checkGraphMonitorResponse:1934  Graph monitor request returned error 549973040[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_READ_REL_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
Traceback (most recent call last):
  File "C:\Program Files (x86)\Intel\openvino_2021.4.752\inference_engine\demos\object_detection_demo\python\object_detection_demo.py", line 361, in <module>
    sys.exit(main() or 0)
  File "C:\Program Files (x86)\Intel\openvino_2021.4.752\inference_engine\demos\object_detection_demo\python\object_detection_demo.py", line 250, in main
    detector_pipeline = AsyncPipeline(ie, model, plugin_config,
  File "C:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\open_model_zoo\demos\common\python\pipelines\async_pipeline.py", line 94, in __init__
    self.exec_net = ie.load_network(network=self.model.net, device_name=device,
  File "ie_api.pyx", line 403, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 442, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Failed to create output FIFO: NC_ERROR
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_READ_REL_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [ncAPI] [         0] [] checkGraphMonitorResponse:1934  Graph monitor request returned error 549972400[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[35mE: [ncAPI] [         0] [] checkGraphMonitorResponse:1934  Graph monitor request returned error 553885968[0m
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_READ_REL_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_CLOSE_STREAM_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_WRITE_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_READ_REL_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_CLOSE_STREAM_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [xLinkWinUsb] [         0] [Scheduler00Thr] usb_bulk_write:467
WinUsb_WritePipe failed with error:=22
[0m
[35mE: [global] [         0] [Scheduler00Thr] dispatcherEventSend:54   Write failed (header) (err -2) | event XLINK_RESET_REQ
[0m
[35mE: [xLink] [         0] [Scheduler00Thr] sendEvents:1132   Event sending failed[0m
[35mE: [ncAPI] [         0] [] ncDeviceClose:1852      Device didn't appear after reboot[0m
```

**Comment by TNTWEN** [comment]
I met this before. And i remember openvino offered solutions in official document.   That's openvino or intel device's  bug,you could also open a question in openvino forum.

**Comment by Hsien0802** [comment]
I have reported the issue, appreciate!
[https://stackoverflow.com/questions/70553690/openvino-yolov4-inference-device-didnt-appear-after-reboot-with-myriad-but-coul](url)
